<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Exceptions - Error Handling on Sujith&#39;s Library</title>
    <link>http://localhost:1313/personal-site/docs/python/7exceptions/</link>
    <description>Recent content in Exceptions - Error Handling on Sujith&#39;s Library</description>
    <generator>Hugo</generator>
    <language>en</language>
    <copyright>Copyright (c) 2020-2024 Thulite</copyright>
    <lastBuildDate>Tue, 11 Feb 2025 23:56:41 +0530</lastBuildDate>
    <atom:link href="http://localhost:1313/personal-site/docs/python/7exceptions/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>07 Exceptions - 01 Errors</title>
      <link>http://localhost:1313/personal-site/docs/python/7exceptions/07-exceptions-01-errors/</link>
      <pubDate>Tue, 11 Feb 2025 23:55:10 +0530</pubDate>
      <guid>http://localhost:1313/personal-site/docs/python/7exceptions/07-exceptions-01-errors/</guid>
      <description>&lt;p&gt;&lt;strong&gt;Exceptions in Python&lt;/strong&gt;&lt;/p&gt;&#xA;&lt;p&gt;Exceptions are special objects in Python that are created to manage errors that arise while the program is running. They allow you to handle unexpected situations without crashing your program.&lt;/p&gt;</description>
    </item>
    <item>
      <title>07 Exceptions - 02 Errors Handling</title>
      <link>http://localhost:1313/personal-site/docs/python/7exceptions/07-exceptions-02-errors-handling/</link>
      <pubDate>Tue, 11 Feb 2025 23:55:42 +0530</pubDate>
      <guid>http://localhost:1313/personal-site/docs/python/7exceptions/07-exceptions-02-errors-handling/</guid>
      <description>&lt;p&gt;&lt;strong&gt;Flow of Control&lt;/strong&gt;&lt;/p&gt;&#xA;&lt;p&gt;When a function calls another function, and an error occurs in the deepest function, the error propagates back to the calling functions unless handled. If the error is not handled at any level, the program will terminate. However, if itâ€™s handled by a &lt;code&gt;try-except&lt;/code&gt; block, the program can continue running.&lt;/p&gt;</description>
    </item>
    <item>
      <title>07 Exceptions - 03 Unit Testing</title>
      <link>http://localhost:1313/personal-site/docs/python/7exceptions/07-exceptions-03-unit-testing/</link>
      <pubDate>Tue, 11 Feb 2025 23:56:06 +0530</pubDate>
      <guid>http://localhost:1313/personal-site/docs/python/7exceptions/07-exceptions-03-unit-testing/</guid>
      <description>&lt;p&gt;Unit testing is a software testing technique where individual units or components of a program are tested in isolation. The goal is to ensure that each function or module works as expected. Unit testing helps catch errors early, provides better documentation, and ensures that the code continues to work correctly as it evolves.&lt;/p&gt;</description>
    </item>
    <item>
      <title>07 Exceptions - 04 ---</title>
      <link>http://localhost:1313/personal-site/docs/python/7exceptions/07-exceptions-04---/</link>
      <pubDate>Tue, 11 Feb 2025 23:56:41 +0530</pubDate>
      <guid>http://localhost:1313/personal-site/docs/python/7exceptions/07-exceptions-04---/</guid>
      <description></description>
    </item>
  </channel>
</rss>
